### ISSUE TITLE
Implement automatic deployment to gh-pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#1]
Please implement Angular2 to gh-pages branch on each commit.

This is already implement in the loklak search project. You can check there for questions as well: https://github.com/fossasia/loklak_search

**Comment by nikhilrayaprolu** [comment]
@mariobehling I looked at the auto deployment code there , 
firstly I have to generate ssh keys and add them on deploy keys here for this repository.
but I couldn't add them since I dont have maintainer rights for it ,so shall I generate the ssh keys and send them to you,so that you can add them here ?

**Comment by mariobehling** [comment]
Let's get @hemantjadon on board.

@hemantjadon Could you help with the setup, please?

**Comment by hemantjadon** [comment]
@mariobehling @nikhilrayaprolu Yes I can definitely help with this.

The code script there automatically takes care of almost all the common cases during building. The thing is to add the deploy keys. and encrypt them, I will add the the keys for now.

**Comment by nikhilrayaprolu** [comment]
@hemantjadon any updates? can you add the deployment keys and update the deploy_key.enc with right keys.

**Comment by mariobehling** [comment]
@nikhilrayaprolu Could you help with this, please?
