### ISSUE TITLE
Videos section should load .mp4 files instead of .gif

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#114]
Currently, videos section is loading .gif files - 

![selection_010](https://cloud.githubusercontent.com/assets/22245418/23889654/346cc40e-08b4-11e7-8bfb-32f1f6f141c6.png)

It should load .mp4 files just like Google - 

![selection_011](https://cloud.githubusercontent.com/assets/22245418/23889659/40526dfa-08b4-11e7-8030-fd78f63dd735.png)

I would like to work on this. :+1:

**Comment by nikhilrayaprolu** [comment]
@harshit98 https://github.com/fossasia/susper.com/blob/angular/src/app/results/results.component.ts#L69
removing gif from this line will do the trick

**Comment by harshit98** [comment]
@nikhilrayaprolu I did this thing. Result came out to be - video section shows nothing!

**Comment by nikhilrayaprolu** [comment]
@harshit98 you worked on this right? what happened why have you closed the pull?

**Comment by harshit98** [comment]
I don't know, I did the work but it was not working, like it was not loading the whole videos section.

**Comment by nikhilrayaprolu** [comment]
@Orbiter this is the data of an individual item we are receiving from the server-side the video results ```

"pubDate":"Thu, 25 Aug 2016 00:00:00 +0000",
"size":"0",
"sizename":"0 byte",
"guid":"FcEjpkJYShOx",
"link":"https://thepiratebay.org/torrent/5033425/Fringe.S01E18.FRENCH.LD.HDTV.XviD-JMT.avi",
"file":"Fringe.S01E18.FRENCH.LD.HDTV.XviD-JMT.avi",
"host":"thepiratebay.org",
"protocol":"https",
"ext":"avi",
"path":"/torrent/5033425",
"title":"Fringe.S01E18.FRENCH.LD.HDTV.XviD-JMT.avi",
"description":""

```
on query to 
http://yacy.searchlab.eu/solr/select?query=d&verify=false&nav=filetype,protocol,hosts,authors,collections,namespace,topics,date&start=0&indexof=off&meanCount=5&resource=global&prefermaskfilter=&rows=10&timezoneOffset=0&fq=url_file_ext_s:(avi+OR+mov+OR+flw+OR+mp4)&wt=yjson&callback=__ng_jsonp__.__req2.finished&facet=true&facet.mincount=1&facet.field=host_s&facet.field=url_protocol_s&facet.field=author_sxt&facet.field=collection_sxt

is there any way to get thumbnails of the videos if possible, so that thumbnails could be displayed beside links for the videos?

**Comment by harshit98** [comment]
@nikhilrayaprolu I tried again to remove `gif` format but it is still not working.

**Comment by nikhilrayaprolu** [comment]
the problem is with having some thumbnail images, where we don't know how to query the server for thumbnails for videos.
