### ISSUE TITLE
translate the documents , and also allow searching in multiple languages

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#129]
translating the documents and allow multi language support using some external translation api's would help enhance susper search.
susper could be completely internationalized into different languages.

**Comment by harshit98** [comment]
@nikhilrayaprolu For internationalization, we can use Angular Translate api - https://angular-translate.github.io/ . It can change language at runtime also and has capabilities of handling pluralization as well.

**Comment by harshit98** [comment]
@nikhilrayaprolu @isuruAb Since, we're working on angular2 - please give your suggestions also so that later we can choose a better translate-api. : )

**Comment by isuruAb** [comment]
@harshit98 that translation API only support for Angular JS.

**Comment by harshit98** [comment]
How about this -> <a href="https://github.com/ngx-translate/core">ngx-translate for angular 2</a> ?

**Comment by nikhilrayaprolu** [comment]
@harshit98 looks like a good choice, proceed with that  package.

**Comment by harshit98** [comment]
@Orbiter Does YaCy supports multiple langauges ? If yes, it should be having a json file for it ?

**Comment by mariobehling** [comment]
This issue is out of scope. There are two topics here, that could be huge.

For example we can have a UI in different languages. We can also discuss how Yacy could give out search results in specific languages only. Or we could also auto-translate documents. All these issues are entirely independent. Translating documents is surely out of scope at this stage of the project. Other issues should be opened separately. 

Closing this therefore.
