### ISSUE TITLE
Links to About Page not to top of Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#204]
Opening About Page does not open to top of page.

**Comment by Marauderer97** [comment]
@mariobehling I am trying to replicate the bug on Google Chrome, but cannot seem to. Clicking on About Page opens to the top of the page. Mozilla Firefox does not cause this error either.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97  you can replicate it by 
1. scroll to some length on search page(until you find  link), now open that link)
2.you will find you at the bottom of the about page.
this is one disadvantage we have with SPAs:-(http://adamsilver.io/articles/the-disadvantages-of-single-page-applications/)
since browser remembers your scroll position,  it assumes you are o the same page, puts you there even though you clicked on another link.One way you can solve this is run a script such that it scrolls to top on a link click.
happy coding :smile:
