### ISSUE TITLE
donot reload whole page

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#209]
when terms button is clicked the whole page gets reloaded, which is a bad design and doesn't follow guidelines of SPA.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu One point though..This however does solve the scroll problem in issue #204 , since it takes us to the start of the page, and no additional script is being run to do this. So do we prevent reloading and run an additional script to fix the scroll position, or do we simply allow reloading?

**Comment by nikhilrayaprolu** [comment]
One of the main advantages of SPAs is it doesn't make calls for repeated data.very nice feature nah!!. But what if we don't use this feature?? you will be retrieving the whole angular library in each call (which will use up a lot data, whether it is server-side or client-side). so better run an additional script.

**Comment by harshit98** [comment]
This issue has been solved. :+1:
