### ISSUE TITLE
Top search bar is not align correctly 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susper.com#238]
<img width="1265" alt="screen shot 2017-05-09 at 2 13 22 am" src="https://cloud.githubusercontent.com/assets/7692626/25824549/743b9748-345d-11e7-8407-33fe70efe947.png">

**Comment by nikhilrayaprolu** [comment]
@marauderer97 https://github.com/fossasia/susper.com/pull/235/files#diff-a029fe59e560678ccc03d8e94ee22e4eR46 this line might be a cause to the error. Can you please look at it.

**Comment by harshit98** [comment]
Anyone working on this ?

**Comment by Marauderer97** [comment]
@harshit98 I am on this @nikhilrayaprolu I am pretty sure that is not the problem, since in the screenshots attached for that pr the bar was fine locally . Looking into it

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu I found the mistake, if the input bar loads before the susper icon is loaded, it assumes the padding% is from the margin, and hence it appears in the line below, if the susper icon has already loaded, then it loads in its correct position. Since the icon generally takes longer to load, we face this problem. Any suggestions on correcting it?
