### ISSUE TITLE
Pagination bar of images not working on refresh

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#254]
Pagination bar in images not working as expected.
Here the pagination bar for images shows 10 pages,
![image](https://cloud.githubusercontent.com/assets/20185076/25899946/6164a170-35af-11e7-885f-4378a9cd16b0.png)

Clicking on any page (say the third), takes the site to all documents, and does not display images any more
![image](https://cloud.githubusercontent.com/assets/20185076/25899999/8de709f4-35af-11e7-97a5-377da4ebfd87.png)

**Comment by harshit98** [comment]
@Marauderer97 Pagination bar of images is working fine.

Page 1 

![selection_016](https://cloud.githubusercontent.com/assets/22245418/25919353/20cc57ce-35ec-11e7-80e9-d65bd476b68e.png)

Page 2

![selection_015](https://cloud.githubusercontent.com/assets/22245418/25919360/2b037a24-35ec-11e7-8d85-7e4b38681b2b.png)

**Page 3** shows empty. It is maybe because of broken image links, they are not loaded. 

![selection_017](https://cloud.githubusercontent.com/assets/22245418/25919397/467fe986-35ec-11e7-85d4-e07cb5a2efcb.png)

These were the results obtained when I typed query `india`.

**Comment by Marauderer97** [comment]
@harshit98 I agree, the bar works fine initially. Now try refreshing the page and view the results.
Before refreshing:
![image](https://cloud.githubusercontent.com/assets/20185076/25994491/a755617e-372b-11e7-8937-ccf2b6400f1e.png)
![image](https://cloud.githubusercontent.com/assets/20185076/25994496/af927458-372b-11e7-902e-41b9188c2128.png)

After refreshing:
![image](https://cloud.githubusercontent.com/assets/20185076/25994516/bfec28ee-372b-11e7-886d-ab7b18478bab.png)
![image](https://cloud.githubusercontent.com/assets/20185076/25994527/cafb403a-372b-11e7-9a5a-0aa0865b6d57.png)

@nikhilrayaprolu Any idea why this is happening?

**Comment by Marauderer97** [comment]
This issue has not been solved, hence re opening.
The pagination bar and the results section both don't work on refresh.
#289 can be viewed as a sub-issue of this.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu 
Notice how it says 1 to 10 results, though it displays 100
![image](https://cloud.githubusercontent.com/assets/20185076/26124530/694ab996-3a9c-11e7-980e-60d7ba7b93fe.png)
Also notice how the pagination bar, should have just 3 pages, but shows 10
![image](https://cloud.githubusercontent.com/assets/20185076/26124553/801a9182-3a9c-11e7-9836-21e78e189c39.png)

**Comment by harshit98** [comment]
Close this issue. It is similar to #289
