### ISSUE TITLE
Images with broken links are being loaded

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#277]
There are some images which are being loaded from server due to which a lot of white space remains (it is shown in red-box).

![selection_025](https://cloud.githubusercontent.com/assets/22245418/26009470/96dba3c2-3766-11e7-9e22-f4244d929f7d.png)

See also #108

**Comment by nikhilrayaprolu** [comment]
can you share an example url that is rendering such images.

**Comment by harshit98** [comment]
@nikhilrayaprolu http://elpandaviral.com/wp-content/uploads/2015/09/INDIA-520x245.jpg

**Comment by Marauderer97** [comment]
@harshit98 Actually, the links are not broken.
Notice the images
![image](https://cloud.githubusercontent.com/assets/20185076/26034570/4d7f882a-38dc-11e7-8c74-61d372576686.png)
for normal images, they get displayed:
![image](https://cloud.githubusercontent.com/assets/20185076/26034579/770df7ee-38dc-11e7-9b98-f8223b40e803.png)
But the broken image icon happens when the image is hosted by a site, say wikipedia, 
![image](https://cloud.githubusercontent.com/assets/20185076/26034583/983ee112-38dc-11e7-84b4-a874c6ec1eb9.png)
@nikhilrayaprolu Since these links end with `.jpg` ones, how can we separate such links in our query from the ones with displayable images? Any ideas?

**Comment by harshit98** [comment]
@Marauderer97 @nikhilrayaprolu maybe this can be a server related issue. Because on http://search.yacy.net/ , the same problem seems to be happen. 

![screenshot from 2017-05-19 16-22-03](https://cloud.githubusercontent.com/assets/22245418/26244951/93e7bf4a-3caf-11e7-89f4-fdb4100c6543.png)

**Comment by harshit98** [comment]
This issue can also be referred to #634

**Comment by praveenojha33** [comment]
This issue can be traced here https://github.com/yacy/yacy_search_server/issues/217
