### ISSUE TITLE
Each character entered in search field results in a rendered page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#371]
Search characters should not be rendered as single pages. Please only render the final input as a page.

See URL field below for comparison.
The browser back button shows five pages for five characters. Expected: It should not show any page 
![screenshot from 2017-05-29 19-33-52](https://cloud.githubusercontent.com/assets/1583873/26558070/514b399c-44a6-11e7-866d-6edbf8a13b4a.png)

if the search result was not finished. Please compare to loklak.net.
![screenshot from 2017-05-29 19-35-48](https://cloud.githubusercontent.com/assets/1583873/26558062/3e441f12-44a6-11e7-98e5-2d417e309928.png)

**Comment by nikhilrayaprolu** [comment]
that's the same case with Google instant search, but Google makes an instant search for "next probable word or a  sentence" rather than each character input.

![screenshot from 2017-05-30 00-17-54](https://cloud.githubusercontent.com/assets/15216503/26559707/fdd93fce-44ce-11e7-96f9-f329d0800644.png)

![screenshot from 2017-05-30 00-16-50](https://cloud.githubusercontent.com/assets/15216503/26559718/075de216-44cf-11e7-88fb-8a008106ecd5.png)
![screenshot from 2017-05-30 00-17-46](https://cloud.githubusercontent.com/assets/15216503/26559719/0761561c-44cf-11e7-8c05-93e51612836b.png)



**how we could implement something similar to Google?**
we just completed building a framework for autocomplete suggestion feature https://github.com/fossasia/susper.com/pull/350 but as this feature is using DBpedia prefix search API, predictions are not as good. Once we are able to find some good API or if we could implement something of that kind by ourselves to make good predictions, we could use those predictions to make a single search to the next probable word, instead of searching for each character input.

**Comment by mariobehling** [comment]
>> Search characters should not be rendered as single pages

> that's the same case with Google instant search, but Google makes an instant search for "next probable word or a sentence" rather than for each character input.

@nikhilrayaprolu Please read the issue details carefully, e.g. Google does not render a page for each character entered.
![screenshot from 2017-05-30 19-50-51](https://cloud.githubusercontent.com/assets/1583873/26597212/89e8412a-4571-11e7-8d65-f8dd066ce063.png)

**Comment by nikhilrayaprolu** [comment]
Yes @mariobehling that might be because you haven't activated instant search.
 I agree that google doesn't render for each character,but it does render for each word when instant search is on.
If instant search is off, one could turn it on from search settings at the bottom right on Google home page

We could make a work around similar to google such that search happens only for whole word rather than each input character

**Comment by AnshulMalik** [comment]
I agree with @mariobehling , it doesn't matter what google does, it doesn't look feel right, let's try and fix this issue.

**Comment by mariobehling** [comment]
@nikhilrayaprolu 

> I agree that google doesn't render for each character,but it does render for each word when instant search is on.

This is not correct when I try. And, we don't want something different to Google, we are looking for something more similar.
![screenshot from 2017-06-05 09-54-27](https://cloud.githubusercontent.com/assets/1583873/26775409/1fed013a-49d5-11e7-88c6-181e17b7fd45.png)

**Comment by harshit98** [comment]
To display results for a particular query, we're using redux for managing the states. Maybe this can be happening because, for each character being entered- a new state is being formed and hence each character is being rendered as single page. Correct me if I'm wrong @nikhilrayaprolu @Marauderer97

**Comment by AnshulMalik** [comment]
I think we are using flux @harshit98. Haven't seen any redux usage yet here in the repo

**Comment by harshit98** [comment]
@AnshulMalik Redux is the implementation of the concept of flux.

**Comment by AnshulMalik** [comment]
Yes @harshit98 , that's correct, redux is the implementation of flux, but there is also a straight forward implementation of flux, which I see we are using right now.
The redux implementation is the more abstracted implementation which is more developer friendly.

**Comment by harshit98** [comment]
@nikhilrayaprolu There is  `onquery()` function in `search-bar.component.ts` which handles this stage whenever a query has been typed. Maybe we can use `debounce()` function to limit calling of a function (which creates a new page) for each character when user typing.. :sweat_smile:

Source - https://davidwalsh.name/javascript-debounce-function

**Comment by nikhilrayaprolu** [comment]
@mariobehling this problem persists even on loklak_search.
![image](https://user-images.githubusercontent.com/15216503/26847837-134e34a6-4b1c-11e7-9248-a3437b8e81d4.png)
each time we change the URL in browser's URL bar, it assumes that we have navigated to a new page.

**Comment by mariobehling** [comment]
The implementation still shows two links back instead of one.
