### ISSUE TITLE
Match alignments of text with market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#381]
Text alignments are not matching market leader.

Compare Susper
![screenshot from 2017-05-30 19-58-00](https://cloud.githubusercontent.com/assets/1583873/26597505/8801975c-4572-11e7-89d7-bb48ef2887d4.png)

With this..
![screenshot from 2017-05-30 19-57-36](https://cloud.githubusercontent.com/assets/1583873/26597518/911c22c6-4572-11e7-9e41-9d674d94c845.png)

**Comment by mariobehling** [comment]
Unfortunately the end of the text is still not aligned properly. Compare:

Google
![screenshot from 2017-07-11 00-36-56](https://user-images.githubusercontent.com/1583873/28043199-1c3dc89a-65d1-11e7-9fac-914dc7b8295e.png)

Susper
![screenshot from 2017-07-11 00-37-47](https://user-images.githubusercontent.com/1583873/28043217-2effe832-65d1-11e7-8e78-f46860e65aad.png)

**Comment by mariobehling** [comment]
The indent of box, submenu and search results is indented further to the left on Susper as well.

**Comment by harshit98** [comment]
@mariobehling I was going through this issue, but it was already solved in #416 

![selection_003](https://user-images.githubusercontent.com/22245418/28184778-5a370478-6832-11e7-8431-dc666a60b922.png)

Alignments were little bit disturbed due to making results page responsive. I have fixed it in PR #639
