### ISSUE TITLE
Correcting the margins and padding of links in top navbar

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#471]
**Actual Behaviour**

The search tabs on hover shows cursor-pointer between the space 'Videos' and 'Tools'

**Expected Behaviour**

The cursor pointer should only be shown, when user hovers over search tabs. And cursor pointer should not be there between space area of 'video' tab and 'tools' tab.

**Screenshots of the issue**

![screenshot from 2017-06-10 01-24-56](https://user-images.githubusercontent.com/22245418/26992358-e8ae58ae-4d7b-11e7-9d0b-6498b7de0dff.png)

**Comment by Marauderer97** [comment]
Actually @harshit98 this is not really an issue, I tried working on it, only to realise Google does the exact same thing. Hover on any of the tabs in Google, even if you are not pointing at text, as long as the cursor is over the underlined portion the cursor is a pointer, only for the short gap between the underlined areas we have the default cursor, susper is doing the exact same thing, the only difference being, we have a slightly lesser gap between our taps when compared to Google, because our underlined area is slightly more, and that is why you are not able to see any difference. So the issue can be changed to correcting the margins and padding of links in top nav bar
