### ISSUE TITLE
Number of results "About.." not aligned

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#491]
Please align this correctly.

![screenshot from 2017-06-16 07-00-14](https://user-images.githubusercontent.com/1583873/27212622-85e35270-5261-11e7-9b09-de842c860c23.png)

**Comment by Marauderer97** [comment]
@harshit98, wasn't there a bug raised on this before, that was fixed by [#416](https://github.com/fossasia/susper.com/pull/416)

**Comment by harshit98** [comment]
Yes @Marauderer97 , It was correctly fixed in #416 . I don't know how this problem is occurring. Look : 

![screenshot from 2017-06-16 12-48-47](https://user-images.githubusercontent.com/22245418/27216221-5ebe2522-5292-11e7-965b-c7d02cbe6932.png)

I did the proper alignment, but now results are not aligned properly again. Also, I'm not gettting `About results` message on susper.

**Comment by nikhilrayaprolu** [comment]
![image](https://user-images.githubusercontent.com/15216503/27232382-80468e50-52d3-11e7-9b7c-12f2d1ead5ac.png)
![image](https://user-images.githubusercontent.com/15216503/27232408-95e3c69c-52d3-11e7-8eeb-5924d061d533.png)

the message in results component is empty but the totalResults in state has some number.

**Comment by harshit98** [comment]
Working on it.

**Comment by nikhilrayaprolu** [comment]
@harshit98 is this issue solved?

**Comment by harshit98** [comment]
@nikhilrayaprolu solved in PR #526
