### ISSUE TITLE
Make suggestion box responsive on the homepage.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#633]
This can issue can be referred to: 
- #604 
- #584 
- #524

**Comment by harshit98** [comment]
This issue is still not solved. 

- [ ] Responsiveness of suggestion box on the results page.
- [ ] Responsiveness of suggestion box on the homepage. 

![screenshot from 2017-07-18 03-31-27](https://user-images.githubusercontent.com/22245418/28291830-cafad344-6b69-11e7-9d9e-b6b95e2f78f6.png)
![screenshot from 2017-07-18 03-31-40](https://user-images.githubusercontent.com/22245418/28291832-ccadd768-6b69-11e7-9e7d-97202559e4f6.png)
![screenshot from 2017-07-18 03-31-47](https://user-images.githubusercontent.com/22245418/28291834-ce6aaf68-6b69-11e7-9135-e97f3786acc0.png)

**Comment by Marauderer97** [comment]
@harshit98 How did you make the page stay in index and not move to results page while you examined the suggestion box width?

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 turn off instant results, and we have an option built for it on search settings page.

**Comment by Marauderer97** [comment]
I have tried working on this for a while now, the problem is we set the search bar dimension to 584 px forcefully in the index page, but we cannot do this for the auto complete box. It is impossible to access the auto-complete box from anywhere else because it is not present until a query is entered I think. This is what happens when I try to access the auto complete box from any .ts file
![image](https://user-images.githubusercontent.com/20185076/28497996-f1cb2d10-6fb1-11e7-8615-0bfc7eed0073.png)
@harshit98 @nikhilrayaprolu Any suggestions are welcome

**Comment by nikhilrayaprolu** [comment]
why do you need to access the auto-complete? just write a class that deals with the width of both search bar and autocomplete and let both inherit this same class

**Comment by harshit98** [comment]
@Marauderer97 The solution looks good by @nikhilrayaprolu

**Comment by Marauderer97** [comment]
@nikhilrayaprolu We need different widths for index and results page. Correct me if I am wrong, but if I write a class in say search bar component, its not enough, so I will have to write it in the index component and hence will have to access it .

**Comment by nikhilrayaprolu** [comment]
Yes, you are right, you have to write the CSS class in the index component.
