### ISSUE TITLE
Sidebar not showing links and clicking on links does not always show results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#733]
1. The sidebar shows links to e.g. authors and a number with the results. Clicking on some links shows no results though. 

2. Scrolling over the links does not show a link URL in the browser bottom bar as usually.

![screenshot from 2017-08-11 21-59-34](https://user-images.githubusercontent.com/1583873/29229836-b75fcf3a-7ee0-11e7-8383-1dbc26c3d5b3.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling there is an error when clicked on Undefined Author, that renders no results. other than that this is working well with other links on my browser, can you please specify if there are other errors too.

can you explain the second point in a bit detail.
working on removing the link for undefined user.

**Comment by harshit98** [comment]
@mariobehling 

Scrolling over the link is showing a link at the bottom of the browser like this, if I hover on top-provider `www.greenpeace.org`:

![screen shot 2017-10-04 at 5 15 45 am](https://user-images.githubusercontent.com/22245418/31154225-4345e7c6-a8c3-11e7-898e-5f55efb251d3.png)

Do you mean it should only show `www.greenpeace.org` or it should show- `https://susper.com/search?query=india%20%20site%3Awww.greenpeace.org&start=0&rows=10&mode=text` at the bottom of the browser on hover?

**Comment by ValentinBercaru** [comment]
Hello @mariobehling ! At the first point, do you mean that by clicking on the links from this screenshot redirects you to a query like: "youtube site:www.youtube.com"? If so, by clicking on a link, would you prefer to be redirected to the website address (and leave susper search engine) or to change the query search to be like: "www.youtube.com" instead of "youtube site:www.youtube.com"?
![img](https://user-images.githubusercontent.com/33882273/36342451-7cfd560c-1407-11e8-8488-d9ce6f3983db.png)

**Comment by praveenojha33** [comment]
Closing it as it has been solved.
