### ISSUE TITLE
Site not loading.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#76]
Whether I go to susper.com or work locally on my machine (localhost:4200) the site ends up loading a default options box.
![screenshot from 2017-02-18 22-14-56](https://cloud.githubusercontent.com/assets/22245418/23095110/8ca4c636-f62a-11e6-82e0-b795da671ede.png)

**Comment by nikhilrayaprolu** [comment]
thats due to addition of '/nav' in this commit https://github.com/fossasia/susper.com/commit/8f9ce597912a8021990143e0df7b2971ab0786b1#diff-17dbed4a514c9206a6d65b113a823ebbR14 
removing it will make everything work well. Also as we don't have any unittests to test if your commit is broken , please commit your changes  only after you recheck that everything is working fine from nexttime.

**Comment by harshit98** [comment]
@nikhilrayaprolu I don't know why I didn't noticed it! Sorry for that.

**Comment by nikhilrayaprolu** [comment]
#78 solved this
