### ISSUE TITLE
Footer in search settings/search settings tab page is not positioning correctly

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#921]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The footer is positioning little higher from the bottom of the settings/search settings tab page

**Expected behavior:**
The footer should be positioned at the bottom of the page

**Screenshots of the issue:**

<img width="1440" alt="screen shot 2018-03-01 at 5 57 55 pm" src="https://user-images.githubusercontent.com/28914919/36848920-af120a9a-1d88-11e8-90e5-d54246d79a0a.png">

**Comment by ValentinBercaru** [comment]
Hello @sathiraumesh ! I tested the `Search Settings` page from :
- Ubuntu 14.04 and 16.04 (both Chrome and Firefox);
- Windows 7 (both Chrome and Firefox);
- Android 4.2, 4.4, 5.0, 6.0 (both Chrome and Firefox);
- Windows Phone 8.1 (Internet Explorer);
and in any browser the footer is placed well.

Are you sure that this bug is not only in your localhost? Did you try to test the `Search Setting` page on [susper.com](https://susper.com)?

Also, I see you're using Safari. Did you try to open the page from another browser (either mobile or desktop)?

**Comment by sathiraumesh** [comment]
Yeah i just went out to the  search setting page on 


<img width="1440" alt="screen shot 2018-03-02 at 10 56 57 am" src="https://user-images.githubusercontent.com/28914919/36884701-85aaa740-1e08-11e8-9726-4cd96411dd86.png">
susper.com and yet the problem exists

**Comment by sathiraumesh** [comment]
The problem also exists in some other pages in different devices for devices like i pad pro the footer seems to be rising up 

<img width="1440" alt="screen shot 2018-03-02 at 12 30 53 pm" src="https://user-images.githubusercontent.com/28914919/36887112-9d02c2d0-1e15-11e8-9905-edff8d0208c1.png">

**Comment by sathiraumesh** [comment]
same for the about us page too
