### ISSUE TITLE
Search bar - not appearing on mobile screen.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#93]
Here is the screenshot of the following bug - 

![screenshot_20170228-094830](https://cloud.githubusercontent.com/assets/22245418/23391711/e8d6ef6e-fd9c-11e6-8518-88b6afd2644f.png)

This issue is similar to issue #84

**Comment by sandeepm96** [comment]
I also noticed it. Its actually because the frontend is not responsive. The search bar appears when the width of the screen is increased.

Here's a screenshot after screen resizing.
![screenshot from 2017-02-28 10 15 28](https://cloud.githubusercontent.com/assets/15105247/23391998/e62c879a-fd9e-11e6-9e05-eda19b526516.png)

**Comment by nikhilrayaprolu** [comment]
closing this issue ,since this is similar to #84 . @harshit98 post this image on issue #84
