### ISSUE TITLE
The titles on the image (main image slider) of an index page are not responsive 

### ISSUE THREAD

**Issue by ShishirBondre** [fossasia/susper.com#94]
I have attached the screenshots please do review it,
The error.png denotes the issue image
and the correct.png refers to correct image
![correct](https://cloud.githubusercontent.com/assets/14989325/23393688/96cbcd4e-fdaa-11e6-865a-c4e26e1f1acb.png)
![issue](https://cloud.githubusercontent.com/assets/14989325/23393689/96cd8544-fdaa-11e6-9621-c54027c6b4c7.png)

**Comment by harshit98** [comment]
@ShishirBondre Here you're not supposed to post issues which are not related to susper.com. If you're new to community - join FOSSASIA communication channels and start contributing to projects you're interested in. Here you can find projects - https://github.com/fossasia . You can post this issue here - https://github.com/fossasia/fossasia.org . Thank you!
@nikhilrayaprolu Please close this issue.
