### ISSUE TITLE
'+' is replaced by [space] in search query.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#962]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Whenever we have a string of '+++...' in our search query it is replaced by ' ' . For eg. if we search for 'c++' it will be replaced by only 'c  ' .

**Expected behavior:**
This behaviour should not occur. 

I am working on it, any suggestions will be helpful.

**Comment by ValentinBercaru** [comment]
Hello @praveenojha33 :smile: ! In the `/src/app/results/results.component.ts` on the line 190, you can see that the '+' is replaced with ' '. I replaced that '+' with ' ' and now the + is not replaced and the results are displayed fine. Teoretically, it replaces the spaces with spaces, so there are no characters changed to the query string. Also, if we remove that condition from the lines 189-191 the Susper first search will not work so that's why I replaced that '+' with ' ' and not removing that condition.

### Demo here:
![screenshot](https://user-images.githubusercontent.com/33882273/37999492-bb092c22-322b-11e8-820f-237df6aaf61b.jpg)

**Comment by praveenojha33** [comment]
@ValentinBercaru I do not understand why we have that condition, Also the results of c,c+++++... are same i.e the results of SearchQuery and SearchQuery+++... is same.

**Comment by praveenojha33** [comment]
@ValentinBercaru Look at the results, look at the susi, it is showing results for letter C.

**Comment by praveenojha33** [comment]
@ValentinBercaru Look at the url the search is done for "c  " not "c++".

**Comment by praveenojha33** [comment]
I think the problem is related to back end because manually changing the url and making query=c++ also not works.

**Comment by ValentinBercaru** [comment]
@praveenojha33 oh yeah, you're right, that condition seems to be useless but removing it, Susper's first search will not work. I just saw that "c++" and "c" return the same results. And yeah, it is probably a back-end problem, but I think it is not Susper's back-end problem because Susper get the results from yach.searchlab.eu. If you search "c++" on yacy searchlab, you will see that the results are the same with the results from Susper for the same query, so the problem of replacing '+' with ' ' can be solved only the way I said.

### Demo:
![idea](https://user-images.githubusercontent.com/33882273/38001262-92028db0-3234-11e8-8449-ce17ac1ed08a.jpg)

**Comment by praveenojha33** [comment]
@ValentinBercaru I think we should leave this issue as it is for now as it is a problem of back end and the condition in which '+' is replaced by space is done intentionally to let user know about the correct search term.

**Comment by praveenojha33** [comment]
This issue can be found here https://github.com/yacy/yacy_search_server/issues/216
